apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: valheim-server
  name: valheim-server
  namespace: valheim-servers
  annotations:
    prometheus.io/scrape: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valheim-server
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
      - image: mbround18/valheim:latest
        name: valheim-server
        ports:
        - containerPort: 2456
          name: valheim-port-01
          protocol: UDP
        - containerPort: 2457
          name: valheim-port-02
          protocol: UDP
        - containerPort: 2458
          name: valheim-port-03
          protocol: UDP
        env:
        - name: PORT
          value: '2456'
        - name: NAME
          value: 'Rathabitat Valheim Server'
        - name: WORLD
          value: 'RatVikings'
        - name: PASSWORD
          value:
        - name: TZ
          value: 'America/Chicago'
        - name: PUBLIC
          value: '1'
        - name: AUTO_UPDATE
          value: '1'
        - name: AUTO_BACKUP
          value: '1'
        - name: AUTO_BACKUP_SCHEDULE
          value: '"0 * * * *"'
        - name: AUTO_BACKUP_REMOVE_OLD
          value: '1'
        - name: AUTO_BACKUP_DAYS_TO_LIVE
          value: '1'
        - name: AUTO_BACKUP_ON_UPDATE
          value: '1'
        - name: AUTO_BACKUP_ON_SHUTDOWN
          value: '1'
        volumeMounts:
        - name: valheim-persistent-storage-saves
          mountPath: /home/steam/.config/unity3d/IronGate/Valheim
        - name: valheim-persistent-storage-server
          mountPath: /home/steam/valheim
        - name: valheim-persistent-storage-backup
          mountPath: /home/steam/backups
        resources:
          limits:
            memory: 5120Mi
            cpu: 4000m
          requests:
            memory: 5120Mi
            cpu: 4000m
      volumes:
      - name: valheim-persistent-storage-saves
        persistentVolumeClaim:
          claimName: valheim-pvc-saves
      - name: valheim-persistent-storage-server
        persistentVolumeClaim:
          claimName: valheim-pvc-server
      - name: valheim-persistent-storage-backup
        persistentVolumeClaim:
          claimName: valheim-pvc-backup