kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-pvc-saves
  namespace: valheim-servers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
  
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-pvc-server
  namespace: valheim-servers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-pvc-backup
  namespace: valheim-servers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi