---
apiVersion: v1
kind: Service
metadata:
  name: valheim-server-tcp
  namespace: valheim-servers
spec:
  type: LoadBalancer
  ports:
  - port: 2456
    name: valheim-port-service-01
    protocol: UDP
  - port: 2457
    name: valheim-port-service-02
    protocol: UDP
  - port: 2458
    name: valheim-port-service-03
    protocol: UDP
  selector:
    app: valheim-server